---
apiVersion: v1
data:
  external.sh: |
    echo -e "This is an example of an external script."
    echo -e "It's running a script with three echo commands in it."
    echo -e "This could be any arbitrary code you want."
kind: ConfigMap
metadata:
  name: external-example
